### PR TITLE
Apache Ant support and some fixes

### LINKED ISSUE #21: Add test case that covers to settings.gradle custom name
By default, a Gradle project's name is the name of its containing directory. You can set a custom name by including
```
rootProject.name = 'newProjectName'
```
in a `settings.gradle` file.

Unclear how widespread this practice is, but if it is, we should have a test case for it.

### LINKED ISSUE #23: Issue graphing "grapher" ident.
https://sourcegraph.com/sourcegraph/srclib-java@04f99061fff6bdf92d21fb18c6fe90544d5fbb0d/.tree/src/main/java/com/sourcegraph/javagraph/GraphCommand.java#startline=262&endline=262

"grapher" is linked to the "grapher" object and the "graph" function.

### PR DESCRIPTION
**Pull request by alexsaveliev**
Added basic Apache Ant support. srclib-java executes the following Ant tasks:
  - property-based (`property`)
  - condition-based (`condition` and derivatives)
 - `mkdir`
 - `get`
 - `javacc`
and extracts information from `javac` tasks (which may be wrapped into `macrodef`).

srclib-java tries to resolve external dependencies by using "search by SHA1" feature of Maven Central.
There are the following limitations:
  - srclib-java does not support custom Ant tasks
  - there will be compilation errors when project contains code based on Ant classes 
  - some Ant tasks may not be executed and some may fail because of requirements not met
  - there may be errors when repository that contains Ant-based project provides build properties file in the form of template (for example, `build.properties.sample`)
  - all source files and classpath entries of all `javac` elements encountered in build.xml file would be merged into single source unit

Fixed #23 
Fixed #21 
Fixed graphing of Gradle-based projects when group name was not set

### CODE REVIEW

**Comment by beyang** [comment]
Add a section to the README describing Ant support (the information provided in the PR description is a good start).

File: src/main/java/com/sourcegraph/javagraph/AntProject.java [hunk 1]
```diff
@@ -0,0 +1,725 @@
...
+    @SuppressWarnings("unchecked")
+    public List<String> getClassPath() {
+        // simply looking in the unit's data, classpath was collected at the "scan" phase
+        return (List<String>) unit.Data.get("ClassPath");
+    }
+
+    @Override
+    @SuppressWarnings("unchecked")
+    public List<String> getBootClassPath() {
+        // simply looking in the unit's data, bootsrap classpath was collected at the "scan" phase
```
Comment (beyang) [inline src/main/java/com/sourcegraph/javagraph/AntProject.java]: s/bootsrap/bootstrap/
